
ALTER TABLE `users` ADD `createdAt` DATETIME NOT NULL DEFAULT '2017-09-17';
ALTER TABLE `users` ADD `updatedAt` DATETIME NOT NULL DEFAULT '2017-09-17';

ALTER TABLE `items` ADD `createdAt` DATETIME NOT NULL DEFAULT '2017-09-17';
ALTER TABLE `items` ADD `updatedAt` DATETIME NOT NULL DEFAULT '2017-09-17';

ALTER TABLE `accounts` ADD `createdAt` DATETIME NOT NULL DEFAULT '2017-09-17';
ALTER TABLE `accounts` ADD `updatedAt` DATETIME NOT NULL DEFAULT '2017-09-17';

ALTER TABLE `balance_history` ADD `createdAt` DATETIME NOT NULL DEFAULT '2017-09-17';
ALTER TABLE `balance_history` ADD `updatedAt` DATETIME NOT NULL DEFAULT '2017-09-17';

ALTER TABLE `transactions` ADD `createdAt` DATETIME NOT NULL DEFAULT '2017-09-17';
ALTER TABLE `transactions` ADD `updatedAt` DATETIME NOT NULL DEFAULT '2017-09-17';
ALTER TABLE `transactions` ADD `deletedAt` DATETIME;
